---
name:             DustBin
main:             presentkim\dustbin\DustBin
version:          1.1.2
api:              [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author:           PresentKim
website:          https://github.com/PMMPPlugin/DustBin
description:      A plugin add dustbin

permissions:
  dustbin.cmd:
    description:  DustBin main command
    default:      true
...
