---
name: DustBin
main: kim\present\dustbin\DustBin
version: 2.1.3
api: [3.0.0, 3.0.0-ALPHA12, 4.0.0]
author: PresentKim
description: Put garbage in the dustbin!

permissions:
  dustbin.cmd:
    description: DustBin main command
    default: true
...
