---
name: DustBin
main: kim\present\dustbin\DustBin
version: 2.0.1
api: [3.0.0, 3.0.0-ALPHA12, 4.0.0]
author: PresentKim
website: https://github.com/PresentKim/DustBin-PMMP
description: Put garbage in the dustbin!

permissions:
  dustbin.cmd:
    description: DustBin main command
    default: true
...
