---
name:             DustBin
main:             blugin\dustbin\DustBin
version:          1.1.4
api:              [3.0.0, 3.0.0-ALPHA11]
author:           PresentKim
website:          https://github.com/Blugin/DustBin-PMMP
description:      A plugin add dustbin

permissions:
  dustbin.cmd:
    description:  DustBin main command
    default:      true
...
