---
name: DustBin
main: kim\present\dustbin\DustBin
version: 2.1.2
api: [4.0.0]
author: PresentKim
website: https://github.com/PresentKim/DustBin-PMMP
description: Put garbage in the dustbin!

permissions:
  dustbin.cmd:
    description: DustBin main command
    default: true
...
